import { LayoutDashboard, Users, CalendarCheck, FileText, ClipboardList, ListChecks, Footprints, GraduationCap, Bell, ListTodo, Award, Settings, BookOpen, Library, CalendarDays, Gauge, NotebookPen, UserPlus, Wallet, FileBarChart, BadgeCheck, MessageSquareHeart, Archive, Layers, TrendingUp, AlarmClock, FileCog, Grid3x3, Database, CalendarOff } from "lucide-react";
import type { NavItem } from "@/components/shell/AppShell";

export const ADMIN_NAV: NavItem[] = [
  { href: "/admin", label: "اللوحة", icon: LayoutDashboard, exact: true, tab: true },
  { href: "/admin/participants", label: "المشاركون", icon: Users, tab: true },
  { href: "/admin/attendance", label: "الحضور", icon: CalendarCheck, tab: true },
  { href: "/admin/reports", label: "التقارير الأسبوعية", icon: FileText, tab: true },
  { href: "/admin/tasks", label: "المهام والتقييم", icon: ClipboardList },
  { href: "/admin/quizzes", label: "الاختبارات", icon: ListChecks },
  { href: "/admin/bank", label: "بنك الأسئلة", icon: Database },
  { href: "/admin/field", label: "اعتماد المعايشة", icon: Footprints },
  { href: "/admin/excuses", label: "طلبات الاستئذان", icon: CalendarOff },
  { href: "/admin/projects", label: "مشاريع التخرج", icon: GraduationCap },
  { href: "/admin/grades", label: "كشف الدرجات", icon: Award },
  { href: "/admin/trends", label: "الاتجاهات", icon: TrendingUp },
  { href: "/admin/diagnostic", label: "التقييم التشخيصي", icon: Gauge },
  { href: "/admin/schedule", label: "جدول البرنامج", icon: CalendarDays },
  { href: "/admin/materials", label: "مكتبة المواد", icon: Library },
  { href: "/admin/minutes", label: "محاضر اللقاءات", icon: NotebookPen },
  { href: "/admin/guests", label: "الخبراء والضيوف", icon: UserPlus },
  { href: "/admin/budget", label: "الميزانية", icon: Wallet },
  { href: "/admin/program-reports", label: "تقارير الجهة", icon: FileBarChart },
  { href: "/admin/certificates", label: "وثائق الإتمام", icon: BadgeCheck },
  { href: "/admin/survey", label: "استبانة الرضا", icon: MessageSquareHeart },
  { href: "/admin/archive", label: "الأرشفة والتصدير", icon: Archive },
  { href: "/admin/phases", label: "مراحل المشروع", icon: ListTodo },
  { href: "/admin/notifications", label: "الإشعارات", icon: Bell, tab: true },
  { href: "/admin/reminders", label: "التذكيرات المجدولة", icon: AlarmClock },
  { href: "/admin/content", label: "محتوى الوثيقة", icon: FileCog },
  { href: "/admin/competencies", label: "مصفوفة الكفاءات", icon: Grid3x3 },
  { href: "/program", label: "وثيقة البرنامج", icon: BookOpen },
  { href: "/admin/cohorts", label: "الدفعات", icon: Layers },
  { href: "/admin/settings", label: "الإعدادات", icon: Settings },
];
